spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zipkin
    username: root
    password: root
  rabbitmq:
    addresses: 172.17.0.2:6372
    username: admin
    password: admin
  redis:
    host: 172.17.0.2
    port: 6379
  thymeleaf:
    cache: false
